name: Docker Build Pipeline

on:
  push:
    branches:
      - 'main'
    paths:
      - 'Dockerfile'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'Dockerfile'
jobs:
  application-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Checkout Pipelines Repository
      uses: actions/checkout@v3
      with:
        repository: 'kiriti07/test-workflow'
        path: '.github/workflows'
        token: ${{ secrets.TOKEN_GIT }}

    - name: Run Application Build
      uses: ./.github/workflows/docker_build.yml
