name: Terraform Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
